# Generated by Django 4.1.7 on 2023-08-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DownloadApp",
            fields=[
                (
                    "timecheck",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="创建时间",
                    ),
                ),
                (
                    "tasknum",
                    models.CharField(default="", max_length=50, verbose_name="Task编号"),
                ),
                (
                    "pkgname",
                    models.CharField(default="", max_length=100, verbose_name="应用包名"),
                ),
                (
                    "apkfilename",
                    models.CharField(
                        default="", max_length=100, verbose_name="apk的文件名字"
                    ),
                ),
                (
                    "apkfilePath",
                    models.CharField(
                        default="", max_length=100, verbose_name="APK报错的路径"
                    ),
                ),
            ],
            options={
                "verbose_name": "下载apk地方",
                "verbose_name_plural": "下载apk地方",
                "db_table": "t_download_app",
            },
        ),
    ]
