# Generated by Django 4.1.7 on 2023-08-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DownloadAPP", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadapp",
            name="apkfilePath",
            field=models.CharField(default="", max_length=200, verbose_name="APK报错的路径"),
        ),
    ]
