# Generated by Django 4.1.7 on 2023-08-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DownloadAPP", "0002_alter_downloadapp_apkfilepath"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadapp",
            name="dversion",
            field=models.CharField(default="", max_length=100, verbose_name="下载的apk版本"),
        ),
    ]
