# Generated by Django 4.2.4 on 2023-08-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DownloadAPP', '0003_downloadapp_dversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadapp',
            name='uploadStatus',
            field=models.CharField(default='', max_length=50, verbose_name='upload的状态'),
        ),
    ]
