# Generated by Django 4.2.4 on 2023-08-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DownloadAPP', '0004_downloadapp_uploadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadapp',
            name='installStatus',
            field=models.CharField(default='', max_length=50, verbose_name='安装状态'),
        ),
    ]
