# Generated by Django 4.2.4 on 2023-11-10 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CheckAPP', '0001_initial'),
        ('CreateAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkversion',
            name='appVerObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckAPP.baseapp', verbose_name='检查版本信息'),
        ),
        migrations.AlterField(
            model_name='favorversion',
            name='appVerObj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckAPP.favorbaseapp', verbose_name='检查版本信息'),
        ),
    ]
